#!/usr/bin/env zsh

# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
# Executes commands before logout.
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

rm -f ${ZDOTDIR:-$ZSHCONF}/zcompdump ${ZDOTDIR:-$ZSHCONF}/zcompdump.zwc
rm -f ${ZDOTDIR:-$ZSHCONF}/zshrc.zwc

# Kill sudo timestamps
# http://www.computerhope.com/unix/sudo.htm
which sudo &>/dev/null && sudo -k
clear

# https://github.com/mhinz/dotfiles/blob/master/.zsh/.zlogout
[[ -n $SSH_CONNECTION ]] && echo -n "Connection closed:  "; date
