# https://github.com/monochromegane/the_platinum_searcher
color = true
color-path = '1;34'
context = 3
hidden = true
ignore = ['.git', 'node_modules']

# Match case insensitively unless PATTERN contains uppercase characters
smart-case = true
